services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - SUPABASE_URL=${SUPABASE_URL}
            - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
        ports:
            - "8000:8000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000"]
            interval: 30s
            timeout: 5s
            retries: 3

    frontend:
        restart: unless-stopped
        # command: npm run start
        build:
            context: ./frontend
            dockerfile: Dockerfile
        environment:
            - API_BASE=${API_BASE:-http://backend:8000}
        ports:
            - "3000:3000"
        depends_on:
            backend:
                condition: service_healthy
