services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: unless-stopped
        image: backend:latest
        container_name: backend
        env_file:
            - .env
        ports:
            - "8000:8000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000"]
            interval: 30s
            timeout: 5s
            retries: 3

    frontend:
        restart: unless-stopped
        image: frontend:latest
        container_name: frontend
        env_file:
            - .env
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            backend:
                condition: service_healthy
